export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const SORT_LIST_REQUEST = "SORT_LIST_REQUEST";
export const SORT_LIST_SUCCESS = "SORT_LIST_SUCCESS";
export const SORT_LIST_FAIL = "SORT_LIST_FAIL";

export const FILTER_LIST_REQUEST = "FILTER_LIST_REQUEST";
export const FILTER_LIST_SUCCESS = "FILTER_LIST_SUCCESS";
export const FILTER_LIST_FAIL = "FILTER_LIST_FAIL";

export const SEARCH_LIST_BY_TITLE_REQUEST = "SEARCH_LIST_BY_TITLE_REQUEST";
export const SEARCH_LIST_BY_TITLE_SUCCESS = "SEARCH_LIST_BY_TITLE_SUCCESS";
export const SEARCH_LIST_BY_TITLE_FAIL = "SEARCH_LIST_BY_TITLE_FAIL";

export const SEARCH_LIST_BY_GENRES_REQUEST = "SEARCH_LIST_BY_GENRES_REQUEST";
export const SEARCH_LIST_BY_GENRES_SUCCESS = "SEARCH_LIST_BY_GENRES_SUCCESS";
export const SEARCH_LIST_BY_GENRES_FAIL = "SEARCH_LIST_BY_GENRES_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAIL_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAIL_FAIL";
